BLINKBUY_SUPER_ADMIN = 'BLINKBUY_SUPER_ADMIN'
BLINKBUY_ADMIN = 'BLINKBUY_ADMIN'
BLINKBUY_CUSTOMER = 'BLINKBUY_CUSTOMER'
BLINKBUY_SHOP_ADMIN = 'BLINKBUY_SHOW_ADMIN'

BLINKBUY_SUPER_ADMIN_LABEL = 'Super Admin'
BLINKBUY_ADMIN_LABEL = 'Admin'
BLINKBUY_CUSTOMER_LABEL = 'Customer'
BLINKBUY_SHOP_ADMIN_LABEL = 'Shop Admin'

BLINKBUY_USER_ROLES = {
    BLINKBUY_SUPER_ADMIN: BLINKBUY_SUPER_ADMIN_LABEL,
    BLINKBUY_ADMIN: BLINKBUY_ADMIN_LABEL,
    BLINKBUY_CUSTOMER: BLINKBUY_CUSTOMER_LABEL,
    BLINKBUY_SHOP_ADMIN: BLINKBUY_SHOP_ADMIN_LABEL,
}
