# Generated by Django 4.2.7 on 2024-01-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Last Modified on')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='bands/images')),
                ('link', models.CharField(max_length=100)),
                ('buttonText', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
