# Generated by Django 4.2.7 on 2024-01-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herobrand',
            name='image',
            field=models.ImageField(upload_to='brands/images'),
        ),
    ]
