# Generated by Django 4.2.7 on 2024-01-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0002_alter_herobrand_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Last Modified on')),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='brands/banner/images')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
