# Generated by Django 4.2.7 on 2024-01-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0004_alter_featuredbanner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredbanner',
            name='sub_title',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
