# Generated by Django 4.2.7 on 2024-02-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
